apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-simple-pod
  labels:
    app: init-pod
spec:
  initContainers:
    - name: init-myservice
      image: arisu1000/simple-container-app:latest
      command: ['sh', '-c', 'sleep 5; echo hello world 01;']
    - name: init-mydb
      image: arisu1000/simple-container-app:latest
      command: ['sh', '-c', 'sleep 5; echo hello world 02;']      
  containers:
    - name: kubernetes-simple-container
      image: arisu1000/simple-container-app:latest
      command: ['sh', '-c', 'sleep 600; echo hello world 03;']
