---
apiVersion: v1
kind: Namespace
metadata:
  name:  prodns

---
apiVersion: v1
kind: Pod
metadata:
  name: my
  namespace: prodns
spec:
  containers:
  - name: my
    image: nginx:1.14
    ports:
    - containerPort: 80
      protocol: TCP

    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
    env:
    - name: DB
      value: mydb