apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainui-stable
spec:
  selector:
    matchLabels:
      app: mainui
      version: stable
  template:
    metadata:
      labels:
        app: mainui
        version: stable
    spec:
      containers:
      - name: nainui
        image: nginx:1.14
        ports:
        - containerPort: 80
