apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      name: apache
      labels: 
        app: main
        rel: stable
    spec:
      containers:
      - name: dep-mainui
        image: httpd:2.2
        ports:
        - containerPort: 80
          protocol: TCP
