---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.233.10.10
  selector: 
    app: webui
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

