apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
spec:
  type: NodePort
  clusterIP: 10.233.10.10
  selector:
    app: webui
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30200