apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
#  completions: 5
#  paralleism: 2
#  activeDeadlineSeconds: 15
  template:
    spec:
      containers:
      - name: job-container-centos
        image: centos:7
        command:
          - bash
        args:
        - "-c"
        - "echo 'Start the pod'; sleep 30; echo 'Stop the pod'"
      restartPolicy: Never
