---
- name: "Disable the service"
  hosts: kube
  gather_facts: no
  tasks:
  - name: "htppd(80), named(53), vsftpd(21)"
    service: 
      name: "{{ item }}"
      state: stopped
      enabled: no
    loop:
    - httpd
    - named
    - vsftpd
